# https://pnpm.io/pnpm-workspace_yaml
---
packages:
  - "packages/*"
  - "apps/*"

# https://pnpm.io/catalogs
catalog:
  "dts-buddy": "^0.5.0"
  "svelte": "^5.14.4"
  "typescript": "^5.7.0"
  "valibot": "1.0.0-beta.9"
  "vite": "^6.0.5"
